name: task
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.0
  provider: ^6.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.3

flutter:

  uses-material-design: true

  fonts:
    - family: Kamerik105
      fonts:
        - asset: fonts/kamerik/Kamerik105-Bold.ttf
          weight: 700
        - asset: fonts/kamerik/Kamerik105-BoldOblique.ttf
          weight: 500
        - asset: fonts/kamerik/Kamerik105-BoldOblique.ttf
        - asset: fonts/kamerik/Kamerik105-Light.ttf
          weight: 400
        - asset: fonts/kamerik/Kamerik105-Thin.ttf
          weight: 300

